// import Hr from "../pages/Hr/Hr";
// import Administration from "../pages/Administration/Administration";
// import Analysis from "../pages/Analysis/Analysis";
import ReviewIcon from "@icons/review-icon.svg?react";
import AdministrationIcon from "@icons/administration-icon.svg?react";
import CarWashIcon from "@icons/car_wash-icon.svg?react";
import PersonnelIcon from "@icons/personnel-icon.svg?react";
import FinancesIcon from "@icons/finances-icon.svg?react";
import MonitoringIcon from "@icons/monitoring-icon.svg?react";
import LoyaltyIcon from "@icons/loyalty-icon.svg?react";
import EquipmentIcon from "@icons/equipment-icon.svg?react";
import WarehouseIcon from "@icons/warehouse-icon.svg?react";
import React from "react";
import Articles from "@/pages/Finance/Articles";
import MonthlyExpanse from "@/pages/Finance/MonthlyExpanse";
import MonthlyExpanseEdit from "@/pages/Finance/MonthlyExpanseEdit";
import DirectoryArticles from "@/pages/Finance/DirectoryArticles";
const Pos = React.lazy(() => import("@/pages/Pos/Pos"));
const Organization = React.lazy(
  () => import("@/pages/Organization/Organization")
);
const DepositDevice = React.lazy(() => import("@/pages/Pos/DepositDevice"));
const ProgramDevices = React.lazy(() => import("@/pages/Pos/ProgramDevices"));
const ProgramDevice = React.lazy(() => import("@/pages/Pos/ProgramDevice"));
const LogIn = React.lazy(() => import("@/pages/Onboarding/LogIn"));
const ProfileForm = React.lazy(() => import("@/pages/Profile/Profile"));
const Default = React.lazy(() => import("@/pages/Default/Default"));
const Register = React.lazy(() => import("@/pages/Onboarding/Register"));
const ForgotPassword = React.lazy(
  () => import("@/pages/Onboarding/ForgotPassword")
);
const Deposit = React.lazy(() => import("@/pages/Pos/Deposit"));
const Programs = React.lazy(() => import("@/pages/Pos/Programs"));
const DepositDevices = React.lazy(() => import("@/pages/Pos/DepositDevices"));
const Dashboard = React.lazy(() => import("@/pages/Dashboard/Dashboard"));
const EquipmentFailure = React.lazy(
  () => import("@/pages/Equipment/EquipmentFailure")
);
const ChemicalConsumption = React.lazy(
  () => import("@/pages/Equipment/ChemicalConsumption")
);
const RoutineWork = React.lazy(() => import("@/pages/Equipment/RoutineWork"));
const RoutineWorkItem = React.lazy(
  () => import("@/pages/Equipment/RoutineWorkItem")
);
const ProgressReport = React.lazy(
  () => import("@/pages/Equipment/ProgressReport")
);
const ProgressReportItem = React.lazy(
  () => import("@/pages/Equipment/ProgressReportItem")
);
const ConsumptionRate = React.lazy(
  () => import("@/pages/Equipment/ConsumptionRate")
);
const InventoryCreation = React.lazy(
  () => import("@/pages/Warehouse/InventoryCreation")
);
const InventoryGroups = React.lazy(
  () => import("@/pages/Warehouse/InventoryGroups")
);
const OverheadCosts = React.lazy(
  () => import("@/pages/Warehouse/OverheadCosts")
);
const Suppliers = React.lazy(() => import("@/pages/Warehouse/Suppliers"));
const InventoryImport = React.lazy(
  () => import("@/pages/Warehouse/InventoryImport")
);
const Documents = React.lazy(() => import("@/pages/Warehouse/Documents"));
const DocumentsCreation = React.lazy(
  () => import("@/pages/Warehouse/DocumentsCreation")
);
const DocumentView = React.lazy(() => import("@/pages/Warehouse/DocumentView"));
const Clients = React.lazy(() => import("@/pages/Marketing/Clients"));
const ShareConstructor = React.lazy(
  () => import("@/pages/Marketing/ShareConstructor")
);
const ClientsImport = React.lazy(
  () => import("@/pages/Marketing/ClientsImport")
);
const Marketing = React.lazy(() => import("@/pages/Marketing/Marketing"));
const ClientsProfile = React.lazy(
  () => import("@/pages/Marketing/ClientsProfile")
);
const BonusProgram = React.lazy(() => import("@/pages/Marketing/BonusProgram"));
const NewSegment = React.lazy(() => import("@/pages/Marketing/NewSegment"));
const Collection = React.lazy(() => import("@/pages/Finance/Collection"));
const CollectionCreation = React.lazy(
  () => import("@/pages/Finance/CollectionCreation")
);
const TimesheetCreation = React.lazy(
  () => import("@/pages/Finance/TimeSheetCreation")
);
const Timesheet = React.lazy(() => import("@/pages/Finance/Timesheet"));
const TimesheetView = React.lazy(() => import("@/pages/Finance/TimesheetView"));
const Timestamps = React.lazy(() => import("@/pages/Finance/Timestamps"));
const IncomeReport = React.lazy(() => import("@/pages/Analysis/IncomeReport"));
const Transactions = React.lazy(() => import("@/pages/Analysis/Transactions"));
const ListOfEmployees = React.lazy(
  () => import("@/pages/Organization/ListOfEmployees")
);
const ListOfRoles = React.lazy(
  () => import("@/pages/Organization/ListOfRoles")
);
const PosConnection = React.lazy(
  () => import("@/pages/Organization/PosConnection")
);
const PlanAct = React.lazy(() => import("@/pages/Pos/PlanAct"));
const InviteUser = React.lazy(() => import("@/pages/Onboarding/InviteUser"));
const Employees = React.lazy(() => import("@/pages/Hr/Employees"));
const Positions = React.lazy(() => import("@/pages/Hr/Positions"));
const SalaryCalculation = React.lazy(
  () => import("@/pages/Hr/SalaryCalculation")
);
const EmployeeAdvance = React.lazy(() => import("@/pages/Hr/EmployeeAdvance"));
const EmployeeProfile = React.lazy(() => import("@/pages/Hr/EmployeeProfile"));
const SalaryCalculationCreation = React.lazy(
  () => import("@/pages/Hr/SalaryCalculationCreation")
);
const Notifications = React.lazy(
  () => import("@/pages/Notifications/Notifications")
);
const RewardsCreation = React.lazy(
  () => import("@/pages/Marketing/RewardsCreation")
);
const EmployeeAdvanceCreation = React.lazy(
  () => import("@/pages/Hr/EmployeeAdvanceCreation")
);
const Subscriptions = React.lazy(
  () => import("@/pages/Organization/Subscriptions")
);
const Analysis = React.lazy(() => import("../pages/Analysis/Analysis"));
const Warehouse = React.lazy(() => import("@/pages/Warehouse/Warehouse"));

const routes = [
  {
    name: "dashboard",
    path: "/",
    subMenu: false,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: ReviewIcon,
    component: Dashboard,
    isSidebar: true,
    permissions: [],
    subNavHeading: "",
    subNav: [],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "administration",
    path: "/administration",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: AdministrationIcon,
    subNavHeading: "",
    component: Default,
    permissions: [
      { action: "manage", subject: "Organization" },
      { action: "create", subject: "Organization" },
      { action: "read", subject: "Organization" },
      { action: "update", subject: "Organization" },
      { action: "delete", subject: "Organization" },
    ],
    subNav: [
      {
        name: "subscriptions",
        filter: false,
        addButton: false,
        addButtonText: "",
        isVisible: true,
        path: "/administration/subscriptions",
        component: Subscriptions,
        permissions: [
          { action: "manage", subject: "Organization" },
          { action: "create", subject: "Organization" },
          { action: "read", subject: "Organization" },
          { action: "update", subject: "Organization" },
          { action: "delete", subject: "Organization" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "accessRights",
        filter: false,
        addButton: false,
        addButtonText: "",
        isVisible: true,
        path: "/administration/accessRights",
        component: Default,
        permissions: [{ action: "manage", subject: "Organization" }],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [
          {
            name: "listOf",
            filter: false,
            addButton: true,
            addButtonText: "add",
            isVisible: true,
            path: "/administration/accessRights/employees",
            component: ListOfEmployees,
            permissions: [{ action: "manage", subject: "Organization" }],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
          {
            name: "listRoles",
            filter: false,
            addButton: false,
            addButtonText: "addR",
            isVisible: true,
            path: "/administration/accessRights/roles",
            component: ListOfRoles,
            permissions: [{ action: "manage", subject: "Organization" }],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
          {
            name: "pos",
            filter: false,
            addButton: false,
            addButtonText: "addR",
            isVisible: true,
            path: "/administration/accessRights/pos/connection",
            component: PosConnection,
            permissions: [{ action: "manage", subject: "Organization" }],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
        ],
        subMenu: true,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "legalEntities",
        filter: true,
        addButton: true,
        addButtonText: "add",
        isVisible: true,
        path: "/administration/legalRights",
        component: Organization,
        permissions: [
          { action: "manage", subject: "Organization" },
          { action: "create", subject: "Organization" },
          { action: "read", subject: "Organization" },
          { action: "update", subject: "Organization" },
          { action: "delete", subject: "Organization" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "objectManagement",
        filter: true,
        addButton: true,
        addButtonText: "add",
        isVisible: true,
        path: "/administration/objectManagement",
        component: Pos,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
    ],
    isSidebar: true,
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "station",
    path: "/station",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: CarWashIcon,
    subNavHeading: "",
    permissions: [
      { action: "manage", subject: "Pos" },
      { action: "create", subject: "Pos" },
      { action: "read", subject: "Pos" },
      { action: "update", subject: "Pos" },
      { action: "delete", subject: "Pos" },
    ],
    subNav: [
      {
        name: "services",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/services",
        component: Default,
        permissions: [{ action: "manage", subject: "Pos" }], // Fixed typo from "manag"
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "deposits",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/enrollments",
        component: DepositDevices,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "depositDevices",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/enrollments/devices",
        component: Deposit,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "depositDevice",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/enrollments/device",
        component: DepositDevice,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "programs",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/programs",
        component: ProgramDevices,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "programDevices",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/programs/devices",
        component: Programs,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "programDevice",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/programs/device",
        component: ProgramDevice,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "planAct",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: true,
        path: "/station/plan/act",
        component: PlanAct,
        permissions: [
          { action: "manage", subject: "Pos" },
          { action: "create", subject: "Pos" },
          { action: "read", subject: "Pos" },
          { action: "update", subject: "Pos" },
          { action: "delete", subject: "Pos" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "cleaning",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/cleaning",
        component: Default,
        permissions: [{ action: "manage", subject: "Pos" }], // Fixed typo from "manag"
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "simpleBoxes",
        filter: true,
        addButton: false,
        addButtonText: "",
        isVisible: false,
        path: "/station/simpleBoxes",
        component: Default,
        permissions: [{ action: "manage", subject: "Pos" }], // Fixed typo from "manag"
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
    ],
    component: Default,
    isSidebar: true,
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "hr",
    path: "/Hr",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: PersonnelIcon,
    component: Default,
    isSidebar: true,
    permissions: [
      { action: "manage", subject: "Hr" },
      { action: "create", subject: "Hr" },
      { action: "read", subject: "Hr" },
      { action: "update", subject: "Hr" },
      { action: "delete", subject: "Hr" },
    ],
    subNavHeading: "",
    subNav: [
      {
        name: "employees",
        filter: true,
        addButton: true,
        addButtonText: "addE",
        isVisible: true,
        path: "/hr/employees",
        component: Employees,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "sid",
        filter: false,
        addButton: true,
        addButtonText: "save",
        isVisible: true,
        path: "/hr/employees/profile",
        component: EmployeeProfile,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "positions",
        filter: false,
        addButton: true,
        addButtonText: "new",
        isVisible: true,
        path: "/hr/positions",
        component: Positions,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: true,
        isHr: true,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "salary",
        filter: true,
        addButton: true,
        addButtonText: "calc",
        isVisible: true,
        path: "/hr/salary",
        component: SalaryCalculation,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "reports",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "sal",
        filter: false,
        addButton: false,
        addButtonText: "calc",
        isVisible: true,
        path: "/hr/salary/creation",
        component: SalaryCalculationCreation,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "reports",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "empAdv",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/hr/employee/advance",
        component: EmployeeAdvance,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "empAdvCreation", // Changed name to avoid duplicate
        filter: false,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/hr/employee/advance/creation",
        component: EmployeeAdvanceCreation,
        permissions: [
          { action: "manage", subject: "Hr" },
          { action: "create", subject: "Hr" },
          { action: "read", subject: "Hr" },
          { action: "update", subject: "Hr" },
          { action: "delete", subject: "Hr" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
    ],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "finance",
    path: "/finance",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: FinancesIcon,
    component: Default,
    isSidebar: true,
    permissions: [
      { action: "manage", subject: "CashCollection" },
      { action: "read", subject: "CashCollection" },
      { action: "create", subject: "CashCollection" },
      { action: "update", subject: "CashCollection" },
      { action: "delete", subject: "CashCollection" },
    ],
    subNavHeading: "",
    subNav: [
      {
        name: "collection",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/finance/collection",
        component: Collection,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "collectionCreation", // Changed name to avoid duplicate
        filter: false,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/finance/collection/creation",
        component: CollectionCreation,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "timestamp",
        filter: false,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/finance/timestamp",
        component: Timestamps,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "period",
        filter: false,
        addButton: false,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/period",
        component: Default,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "employee",
        filter: true,
        addButton: true,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/timesheet",
        component: Timesheet,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "employeeCreation", // Changed name to avoid duplicate
        filter: false,
        addButton: false,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/timesheet/creation",
        component: TimesheetCreation,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "abcd",
        filter: false,
        addButton: false,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/timesheet/view",
        component: TimesheetView,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "financial",
        filter: true,
        addButton: true,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/financial/accounting",
        component: Default,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: true,
        titleName: "",
        subNav: [
          {
            name: "articles",
            filter: true,
            addButton: false,
            addButtonText: "add",
            isVisible: true,
            path: "/finance/financial/accounting/articles",
            component: Articles,
            permissions: [
              { action: "manage", subject: "CashCollection" },
              { action: "read", subject: "CashCollection" },
              { action: "create", subject: "CashCollection" },
              { action: "update", subject: "CashCollection" },
              { action: "delete", subject: "CashCollection" },
            ],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
          {
            name: "direct",
            filter: false,
            addButton: true,
            addButtonText: "add",
            isVisible: true,
            path: "/finance/financial/accounting/directory/articles",
            component: DirectoryArticles,
            permissions: [
              { action: "manage", subject: "CashCollection" },
              { action: "read", subject: "CashCollection" },
              { action: "create", subject: "CashCollection" },
              { action: "update", subject: "CashCollection" },
              { action: "delete", subject: "CashCollection" },
            ],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
          {
            name: "appo",
            filter: true,
            addButton: true,
            addButtonText: "add",
            isVisible: true,
            path: "/finance/financial/accounting/directory/appointments",
            component: Default,
            permissions: [
              { action: "manage", subject: "CashCollection" },
              { action: "read", subject: "CashCollection" },
              { action: "create", subject: "CashCollection" },
              { action: "update", subject: "CashCollection" },
              { action: "delete", subject: "CashCollection" },
            ],
            isSidebar: true,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
          },
        ],
        subMenu: true,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "reportFor",
        filter: true,
        addButton: true,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/report/period",
        component: MonthlyExpanse,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "from",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "reportForEdit", // Changed name to avoid duplicate
        filter: false,
        addButton: false,
        addButtonText: "add",
        isVisible: true,
        path: "/finance/report/period/edit",
        component: MonthlyExpanseEdit,
        permissions: [
          { action: "manage", subject: "CashCollection" },
          { action: "read", subject: "CashCollection" },
          { action: "create", subject: "CashCollection" },
          { action: "update", subject: "CashCollection" },
          { action: "delete", subject: "CashCollection" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
    ],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "analysis",
    path: "/analysis",
    subMenu: true,
    filter: true,
    addButton: false,
    addButtonText: "",
    icon: MonitoringIcon,
    component: Default,
    isSidebar: true,
    permissions: [
      { action: "manage", subject: "ShiftReport" },
      { action: "create", subject: "ShiftReport" },
      { action: "read", subject: "ShiftReport" },
      { action: "update", subject: "ShiftReport" },
      { action: "delete", subject: "ShiftReport" },
    ],
    subNavHeading: "",
    subNav: [
      {
        name: "analysis",
        filter: true,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/analysis/all",
        component: Analysis,
        permissions: [
          { action: "manage", subject: "ShiftReport" },
          { action: "create", subject: "ShiftReport" },
          { action: "read", subject: "ShiftReport" },
          { action: "update", subject: "ShiftReport" },
          { action: "delete", subject: "ShiftReport" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "income",
        filter: false,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/analysis/report",
        component: IncomeReport,
        permissions: [
          { action: "manage", subject: "ShiftReport" },
          { action: "create", subject: "ShiftReport" },
          { action: "read", subject: "ShiftReport" },
          { action: "update", subject: "ShiftReport" },
          { action: "delete", subject: "ShiftReport" },
        ],
        isSidebar: false,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
      {
        name: "my",
        filter: true,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/analysis/transactions",
        component: Transactions,
        permissions: [
          { action: "manage", subject: "ShiftReport" },
          { action: "create", subject: "ShiftReport" },
          { action: "read", subject: "ShiftReport" },
          { action: "update", subject: "ShiftReport" },
          { action: "delete", subject: "ShiftReport" },
        ],
        isSidebar: true,
        isHr: false,
        titleName: "",
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
      },
    ],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "marketing",
    path: "/marketing",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: LoyaltyIcon,
    subNavHeading: "",
    subNav: [
      {
        name: "clients",
        filter: true,
        addButton: true,
        addButtonText: "addClient",
        isVisible: true,
        path: "/marketing/clients",
        component: Clients,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "importClients",
        filter: true,
        addButton: false,
        addButtonText: "addClient",
        isVisible: true,
        path: "/marketing/clients/import",
        component: ClientsImport,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "clientProfile",
        filter: false,
        addButton: false,
        addButtonText: "edit",
        isVisible: true,
        path: "/marketing/clients/profile",
        component: ClientsProfile,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "segments",
        filter: false,
        addButton: false,
        addButtonText: "addSeg",
        isVisible: true,
        path: "/marketing/segments",
        component: Default,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "createSeg",
        filter: false,
        addButton: false,
        addButtonText: "addSeg",
        isVisible: true,
        path: "/marketing/segments/new",
        component: NewSegment,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "share",
        filter: false,
        addButton: false,
        addButtonText: "report",
        isVisible: true,
        path: "/marketing/share/constructor",
        component: Default,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "loyalty",
        filter: false,
        addButton: true,
        addButtonText: "newPromo",
        isVisible: true,
        path: "/marketing/loyalty",
        component: ShareConstructor,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "bonus",
        filter: false,
        addButton: false,
        addButtonText: "newPromo",
        isVisible: true,
        path: "/marketing/loyalty/rewards",
        component: RewardsCreation,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "bonusProgram", // Changed name to avoid duplicate
        filter: false,
        addButton: false,
        addButtonText: "newPromo",
        isVisible: true,
        path: "/marketing/loyalty/bonus",
        component: BonusProgram,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "marketRes",
        filter: false,
        addButton: false,
        addButtonText: "report",
        isVisible: true,
        path: "/marketing/market/research",
        component: Default,
        permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
    ],
    component: Marketing,
    isSidebar: true,
    permissions: [{ action: "manage", subject: "LoyaltyProgram" }],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "equipment",
    path: "/equipment",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: EquipmentIcon,
    subNavHeading: "dailyOptions",
    subNav: [
      {
        name: "chemical",
        filter: true,
        addButton: false,
        addButtonText: "report",
        isVisible: true,
        path: "/equipment/chemical/consumption",
        component: ChemicalConsumption,
        permissions: [
          { action: "manage", subject: "TechTask" },
          { action: "create", subject: "TechTask" },
          { action: "read", subject: "TechTask" },
          { action: "update", subject: "TechTask" },
          { action: "delete", subject: "TechTask" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "routine",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/equipment/routine/work",
        component: RoutineWork,
        permissions: [
          { action: "manage", subject: "TechTask" },
          { action: "create", subject: "TechTask" },
          { action: "read", subject: "TechTask" },
          { action: "update", subject: "TechTask" },
          { action: "delete", subject: "TechTask" },
        ],
        isSidebar: true,
        subNav: [
          {
            name: "list",
            filter: true,
            addButton: true,
            addButtonText: "create",
            isVisible: true,
            path: "/equipment/routine/work/list",
            component: RoutineWork,
            permissions: [
              { action: "manage", subject: "TechTask" },
              { action: "create", subject: "TechTask" },
              { action: "read", subject: "TechTask" },
              { action: "update", subject: "TechTask" },
              { action: "delete", subject: "TechTask" },
            ],
            isSidebar: true,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
          },
          {
            name: "listItem", // Changed name to avoid duplicate
            filter: false,
            addButton: false,
            addButtonText: "create",
            isVisible: true,
            path: "/equipment/routine/work/list/item",
            component: RoutineWorkItem,
            permissions: [
              { action: "manage", subject: "TechTask" },
              { action: "create", subject: "TechTask" },
              { action: "read", subject: "TechTask" },
              { action: "update", subject: "TechTask" },
              { action: "delete", subject: "TechTask" },
            ],
            isSidebar: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
          },
          {
            name: "progress",
            filter: true,
            addButton: false,
            addButtonText: "create",
            isVisible: true,
            path: "/equipment/routine/work/progress",
            component: ProgressReport,
            permissions: [
              { action: "manage", subject: "TechTask" },
              { action: "create", subject: "TechTask" },
              { action: "read", subject: "TechTask" },
              { action: "update", subject: "TechTask" },
              { action: "delete", subject: "TechTask" },
            ],
            isSidebar: true,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
          },
          {
            name: "progressItem", // Changed name to avoid duplicate
            filter: false,
            addButton: false,
            addButtonText: "create",
            isVisible: true,
            path: "/equipment/routine/work/progress/item",
            component: ProgressReportItem,
            permissions: [
              { action: "manage", subject: "TechTask" },
              { action: "create", subject: "TechTask" },
              { action: "read", subject: "TechTask" },
              { action: "update", subject: "TechTask" },
              { action: "delete", subject: "TechTask" },
            ],
            isSidebar: false,
            subNavHeading: "",
            isPublicRoute: false,
            isImport: false,
            isHr: false,
            titleName: "",
            subNav: [],
            subMenu: false,
          },
        ],
        subMenu: true,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "consumption",
        filter: true,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/equipment/consumption/rate",
        component: ConsumptionRate,
        permissions: [],
        isSidebar: true,
        subNav: [],
        isHr: true,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        titleName: "",
        subMenu: false,
      },
      {
        titleName: "from",
        name: "equipmentFailure",
        filter: true,
        addButton: true,
        addButtonText: "fix",
        isVisible: true,
        path: "/equipment/failure",
        component: EquipmentFailure,
        permissions: [
          { action: "manage", subject: "Incident" },
          { action: "create", subject: "Incident" },
          { action: "read", subject: "Incident" },
          { action: "update", subject: "Incident" },
          { action: "delete", subject: "Incident" },
        ],
        isSidebar: true,
        subNav: [],
        isHr: true,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        subMenu: false,
      },
      {
        titleName: "settings",
        name: "replacing",
        filter: false,
        addButton: false,
        addButtonText: "fix",
        isVisible: true,
        path: "/equipment/replacing/programs",
        component: Default,
        permissions: [],
        isSidebar: true,
        subNav: [],
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        subMenu: false,
      },
    ],
    component: Default,
    isSidebar: true,
    permissions: [
      { action: "manage", subject: "Incident" },
      { action: "create", subject: "Incident" },
      { action: "read", subject: "Incident" },
      { action: "update", subject: "Incident" },
      { action: "delete", subject: "Incident" },
      { action: "manage", subject: "TechTask" },
      { action: "create", subject: "TechTask" },
      { action: "read", subject: "TechTask" },
      { action: "update", subject: "TechTask" },
      { action: "delete", subject: "TechTask" },
    ],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "store",
    path: "/warehouse",
    subMenu: true,
    filter: false,
    addButton: false,
    addButtonText: "",
    icon: WarehouseIcon,
    component: Default,
    isSidebar: true,
    subNavHeading: "",
    subNav: [
      {
        name: "ware",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/create",
        component: Warehouse,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        isImport: true,
        subNavHeading: "",
        isPublicRoute: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "nomenclature",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/inventory",
        component: InventoryCreation,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        isImport: true,
        subNavHeading: "",
        isPublicRoute: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "import",
        filter: false,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/inventory/import",
        component: InventoryImport,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "groups",
        filter: false,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/inventoryGroups",
        component: InventoryGroups,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "documents",
        filter: true,
        addButton: true,
        addButtonText: "createDo",
        isVisible: true,
        path: "/warehouse/documents",
        component: Documents,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "createDo",
        filter: false,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/documents/creation",
        component: DocumentsCreation,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "createDoView", // Changed name to avoid duplicate
        filter: false,
        addButton: true,
        addButtonText: "edit",
        isVisible: true,
        path: "/warehouse/documents/view",
        component: DocumentView,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: false,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "left",
        filter: true,
        addButton: false,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/leftovers",
        component: OverheadCosts,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
      {
        name: "suppliers",
        filter: true,
        addButton: true,
        addButtonText: "create",
        isVisible: true,
        path: "/warehouse/suppliers",
        component: Suppliers,
        permissions: [
          { action: "manage", subject: "Warehouse" },
          { action: "read", subject: "Warehouse" },
          { action: "create", subject: "Warehouse" },
          { action: "update", subject: "Warehouse" },
          { action: "delete", subject: "Warehouse" },
        ],
        isSidebar: true,
        subNav: [],
        subMenu: false,
        subNavHeading: "",
        isPublicRoute: false,
        isImport: false,
        isHr: false,
        titleName: "",
      },
    ],
    permissions: [
      { action: "manage", subject: "Warehouse" },
      { action: "read", subject: "Warehouse" },
      { action: "create", subject: "Warehouse" },
      { action: "update", subject: "Warehouse" },
      { action: "delete", subject: "Warehouse" },
    ],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "Register",
    path: "/register",
    subMenu: false,
    component: Register,
    isSidebar: false,
    isPublicRoute: true,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "Login",
    path: "/login",
    subMenu: false,
    component: LogIn,
    isSidebar: false,
    isPublicRoute: true,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "Forgot Password",
    path: "/forgotPassword",
    subMenu: false,
    component: ForgotPassword,
    isSidebar: false,
    isPublicRoute: true,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "Invite User",
    path: "/inviteUser",
    subMenu: false,
    component: InviteUser,
    isSidebar: false,
    isPublicRoute: true,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "profile",
    path: "/profile",
    subMenu: false,
    component: ProfileForm,
    isSidebar: false,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
  {
    name: "notifications",
    path: "/notifications",
    subMenu: false,
    component: Notifications,
    isSidebar: false,
    permissions: [],
    filter: false,
    addButton: false,
    addButtonText: "",
    subNavHeading: "",
    subNav: [],
    isPublicRoute: false,
    isImport: false,
    isHr: false,
    titleName: "",
    isVisible: true,
  },
];

export default routes;
